# Defined in torch/csrc/hip/shared/roctx.cpp

def markA(msg: str) -> None: ...
def rangeEnd(range_id: int) -> None: ...
def rangePop() -> int: ...
def rangePushA(msg: str) -> int: ...
def rangeStartA(msg: str) -> int: ...
def deviceRangeStart(msg: str, stream_ptr: int) -> object: ...
def deviceRangeEnd(range_handle: object, stream_ptr: int) -> None: ...
